mongo: &mongo_defaults
  mongo_uri: "mongodb://localhost:27020"
  db_name: "aisdk"
  raw_collection: "raw"
  clean_collection: "clean"

ingest:
  <<: *mongo_defaults
  num_workers: 4
  input_file: "data/input/aisdk-2025-05-01.csv"
  max_rows: 1000000
  batch_size: 50000

filter_noise:
  <<: *mongo_defaults
  num_workers: 4

calculate_statistics:
  <<: *mongo_defaults
  output_dir: "data/output"
